#include <catch2/catch_test_macros.hpp>

#include "ncbind.hpp"

TEST_CASE("first-pass compatibility stubs are registered") {
    const tjs_char *modules[] = {
        TJS_W("flashPlayer.dll"),
        TJS_W("layerExSubImage.dll"),
        TJS_W("layerExSave.dll"),
        TJS_W("gfxEffect.dll"),
        TJS_W("clipboardEx.dll"),
        TJS_W("shellExecute.dll"),
        TJS_W("process.dll"),
        TJS_W("tasktray.dll"),
        TJS_W("adjustMonitor.dll"),
        TJS_W("fpslimit.dll"),
        TJS_W("systemEx.dll"),
        TJS_W("htmlhelp.dll"),
        TJS_W("httprequest.dll"),
        TJS_W("drawdevice.dll"),
        TJS_W("drawdeviceD3D.dll"),
        TJS_W("drawdeviceIrrlicht.dll"),
        TJS_W("drawdeviceOgre.dll"),
        TJS_W("drawdeviceZ_D3D9.dll"),
        TJS_W("gameswf.dll"),
        TJS_W("httpserv.dll"),
        TJS_W("javascript.dll"),
        TJS_W("layerEx.dll"),
        TJS_W("xmlhttprequest.dll"),
        TJS_W("msgreceiver.dll"),
        TJS_W("messenger.dll"),
        TJS_W("oleclass.dll"),
        TJS_W("registory.dll"),
        TJS_W("resourceRW.dll"),
        TJS_W("shrinkCopy.dll"),
        TJS_W("sigcheck.dll"),
        TJS_W("sqlite3_xp3_vfs.dll"),
        TJS_W("stdio.dll"),
        TJS_W("tftSave.dll"),
        TJS_W("videoEncoder.dll"),
        TJS_W("windowExProgress.dll"),
        TJS_W("wmrdump.dll"),
        TJS_W("wsh.dll"),
        TJS_W("wumsadp.dll"),
        TJS_W("layerExAgg.dll"),
        TJS_W("layerExCairo.dll"),
        TJS_W("layerExGdiPlus.dll"),
        TJS_W("magickpp.dll"),
        TJS_W("mkpj.dll"),
        TJS_W("onigruma.dll"),
        TJS_W("squirrel.dll"),
        TJS_W("xpressive.dll"),
        TJS_W("zlib.dll"),
        TJS_W("binaryStream.dll"),
        TJS_W("base64.dll"),
        TJS_W("encode.dll"),
        TJS_W("expat.dll"),
        TJS_W("imagesaver.dll"),
        TJS_W("json.dll"),
        TJS_W("lineParser.dll"),
        TJS_W("memfile.dll"),
        TJS_W("minizip.dll"),
        TJS_W("qrcode.dll"),
        TJS_W("sqlite3.dll"),
    };

    for(const auto *module : modules)
        CHECK(ncbAutoRegister::HasModule(module));
}
